language: java
jdk:
 - oraclejdk8
services:
  - mysql
before_install:
  - mysql -u root --password="" < src/test/java/com/sysco/ordermanager/travis.sql
install:
  - mvn install -DskipTests
jobs:
  include:
    - stage: test
      script: mvn  test
    - stage: deploy
      script: mvn spring-boot:run
